version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(deps)"
    open-pull-requests-limit: 15
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(deps)"
    open-pull-requests-limit: 15
    groups:
      react-router:
        patterns:
          - "react-router"
          - "@react-router/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      vite:
        patterns:
          - "vite"
          - "vite-*"
      express-types:
        patterns:
          - "@types/express"
          - "@types/express-serve-static-core"
      bootstrap:
        patterns:
          - "bootstrap"
          - "react-bootstrap"
      remix-auth:
        patterns:
          - "remix-auth"
          - "remix-auth-*"

  - package-ecosystem: "nuget"
    directory: "/backend"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(deps)"
    open-pull-requests-limit: 15
    groups:
      dotnet:
        patterns:
          - "Microsoft.AspNetCore.*"
          - "Microsoft.EntityFrameworkCore.*"