// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NzbWebDAV.Database;

#nullable disable

namespace NzbWebDAV.Database.MetricsMigrations
{
    [DbContext(typeof(MetricsDbContext))]
    partial class MetricsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("NzbWebDAV.Database.Models.Metrics.CatalogueDaily", b =>
                {
                    b.Property<long>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AddedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RemovedCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Day");

                    b.ToTable("CatalogueDaily", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.Metrics.MetricEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<long?>("Num")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RefId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Kind", "At");

                    b.ToTable("MetricEvents", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.Metrics.ProviderHourly", b =>
                {
                    b.Property<long>("Hour")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("Articles")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesFetched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Errors")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("P95DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Retries")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SumDurationMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Hour", "Provider");

                    b.ToTable("ProviderHourly", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.Metrics.ProviderMinute", b =>
                {
                    b.Property<long>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("Articles")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesFetched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Errors")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Hist")
                        .HasColumnType("BLOB");

                    b.Property<long>("Retries")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SumDurationMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Minute", "Provider");

                    b.ToTable("ProviderMinutes", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.Metrics.ReadSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesFetched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesServed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientUserAgent")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndReason")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Path");

                    b.HasIndex("StartedAt");

                    b.ToTable("ReadSessions", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.Metrics.SegmentFetch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("At")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Bytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("QueueItemId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReadSessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Retries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("Provider", "At");

                    b.ToTable("SegmentFetches", (string)null);
                });

            modelBuilder.Entity("NzbWebDAV.Database.Models.Metrics.ThroughputMinute", b =>
                {
                    b.Property<long>("Minute")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActiveReadsMax")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Articles")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesFetched")
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesServed")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Errors")
                        .HasColumnType("INTEGER");

                    b.HasKey("Minute");

                    b.ToTable("ThroughputMinutes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
