declare const styles: {
  readonly container: string;
  readonly header: string;
  readonly title: string;
  readonly sub: string;
  readonly hero: string;
  readonly heroMain: string;
  readonly heroNum: string;
  readonly heroLabel: string;
  readonly heroAside: string;
  readonly heroAsideNum: string;
  readonly heroAsideLabel: string;
  readonly plot: string;
  readonly bar: string;
  readonly barActive: string;
  readonly seg: string;
  readonly footer: string;
  readonly hoverLine: string;
  readonly hint: string;
  readonly legend: string;
  readonly legendItem: string;
  readonly swatch: string;
  readonly legendName: string;
  readonly legendNum: string;
  readonly empty: string;
  readonly emptySub: string;
};
export = styles;
